### ISSUE TITLE
Still being maintained?

### ISSUE THREAD

**Issue by IGx89** [adobe/xamarin-acpcore#24]
Hello! We're in the process of updating our Xamarin (Native) app from the v4 Adobe Analytics to this. This looks great -- thanks for building the Xamarin bindings! -- but I'm a bit confused why the version is 0.0.1 and it hasn't been updated in a year even though the native packages have had many updates. Is this supported for production applications and will continue to be updated?

Thanks!

**Comment by yangyansong-adbe** [comment]
Hi @IGx89 ,
We're working on the `1.0.0` release with the latest native packages/binaries, the build will be out very soon.

Thanks,
Yansong

**Comment by IGx89** [comment]
That's great news, thanks for the update Yansong!

**Comment by stcheng-adobe** [comment]
Hi @IGx89,

We have updated ACPCore wrapper to 1.0.0, more details here: https://aep-sdks.gitbook.io/docs/resources/upgrading-to-aep/current-sdk-versions#xamarin.  And we are planning to update ACPAnalytics to 1.0.0 shortly.  We keep you posted once the wrapper for Analytics is done.

Thanks,
Stephen

**Comment by IGx89** [comment]
Thanks! Ready to start testing once ACPAnalytics is updated

**Comment by IGx89** [comment]
Hello @stcheng-adobe! Any ETA on the ACPAnalytics update? Trying to decide if we go forward with testing/rolling out 0.0.1, or if we should wait for 1.0.0. Thanks!

**Comment by stcheng-adobe** [comment]
Hi @IGx89,

We are planning to  release the update this week.  I will let you know once the build is ready.

Thanks,
Stephen

**Comment by stcheng-adobe** [comment]
Hi @IGx89 ,

We have released ACPAnalytics 1.0.0 today.  I am closing this issue for now and please let us know if you are running into other issues.

Thanks,
Stephen
