### ISSUE TITLE
Adobe Campaign for Xamarin?

### ISSUE THREAD

**Issue by narciszait** [adobe/xamarin-acpcore#25]
Hi,

   Would the Adobe Campaign native frameworks be included in a Xamarin Nuget?
   I have tried taking the latest iOS version of APCampaign and create a Binding Xamarin project but it fails at native linking.
   It would really be of great help to have Adobe Campaign for Xamarin.

**Comment by praschetan** [comment]
@narciszait  - we don't plan to support Adobe Campaign Standard via Xamarin at this time. Recommend contacting your Adobe Customer Success Manager if this is something you need for us to prioritize.
