### ISSUE TITLE
.Net6 or .Net7 update

### ISSUE THREAD

**Issue by deyupopp** [adobe/xamarin-acpcore#31]
Since Xamarin will be out of support in 2024, are there any plans to migrate this to .Net6 or .Net7? 
https://github.com/xamarin/xamarin-macios/issues/13087

**Comment by spoorthipujariadobe** [comment]
Hi @deyupopp,
We will not be migrating out Xamarin SDKs or enhancing it in anyway going forward given the low customer use.

Regards,
Spoorthi
